# Enterprise: Team-based AWS foundation
# ======================================
# Complete multi-account architecture with account-per-team model:
# - Teams OU with dedicated accounts per team
# - Security and Platform accounts for centralized services
# - Delegated administration (SSO, IPAM from platform account)
# - IPAM pools shared via RAM to Teams OU
# - Each team gets their own VPC with dual-stack networking
#
# This example creates:
# - 1 AWS Organization
# - 6 Organizational Units (Security, Platform, Teams/Alpha, Teams/Beta, Teams/Data)
# - 5 Member Accounts (security, platform, alpha, beta, data)
# - 2 Delegated Administrators (SSO, IPAM to platform)
# - 5 Identity Store Groups (per-team + admins + security)
# - Team-specific permission sets
# - IPAM with hierarchical pools shared to Teams OU
# - VPCs in each team account
#
# Why account-per-team?
# - Blast radius isolation between teams
# - Clear cost attribution
# - Teams own their infrastructure, platform provides guardrails

apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: Foundation
metadata:
  name: acme
  namespace: acme
spec:
  managementPolicies: ["*"]

  aws:
    providerConfig: aws-management-account
    region: us-east-1

  tags:
    organization: acme
    managed-by: crossplane

  # ---------------------------------------------------------------------------
  # Organization Settings
  # ---------------------------------------------------------------------------
  organization:
    awsServiceAccessPrincipals:
      - iam.amazonaws.com
      - sso.amazonaws.com
      - account.amazonaws.com
      - ipam.amazonaws.com
      - ram.amazonaws.com

  # ---------------------------------------------------------------------------
  # Organizational Unit Hierarchy (Team-based)
  # ---------------------------------------------------------------------------
  # Root
  # ├── Security          (security tooling, audit)
  # ├── Platform          (shared services, IPAM admin, CI/CD)
  # └── Teams
  #     ├── Alpha         (product team Alpha)
  #     ├── Beta          (product team Beta)
  #     └── Data          (data engineering team)

  organizationalUnits:
    - path: Security
    - path: Platform
    - path: Teams
    - path: Teams/Alpha
    - path: Teams/Beta
    - path: Teams/Data

  # ---------------------------------------------------------------------------
  # Accounts (Team-based)
  # ---------------------------------------------------------------------------
  accounts:
    # Security account - GuardDuty, Security Hub, CloudTrail
    - name: acme-security
      email: aws-security@acme.example.com
      ou: Security
      tags:
        team: security

    # Platform - Identity Center admin, IPAM admin, CI/CD, shared tooling
    - name: acme-platform
      email: aws-platform@acme.example.com
      ou: Platform
      tags:
        team: platform

    # Team accounts - each team owns their account
    - name: acme-alpha
      email: aws-alpha@acme.example.com
      ou: Teams/Alpha
      tags:
        team: alpha

    - name: acme-beta
      email: aws-beta@acme.example.com
      ou: Teams/Beta
      tags:
        team: beta

    - name: acme-data
      email: aws-data@acme.example.com
      ou: Teams/Data
      tags:
        team: data

  # ---------------------------------------------------------------------------
  # Delegated Administrators
  # ---------------------------------------------------------------------------
  # Delegate SSO and IPAM administration to platform account
  delegatedAdministrators:
    - servicePrincipal: sso.amazonaws.com
      account: acme-platform
    - servicePrincipal: ipam.amazonaws.com
      account: acme-platform

  # ---------------------------------------------------------------------------
  # Identity Center
  # ---------------------------------------------------------------------------
  identityCenter:
    region: us-east-1
    identityStoreId: d-1234567890
    instanceArn: arn:aws:sso:::instance/ssoins-abcdef0123456789

    # Groups - one per team plus admins and security
    groups:
      - name: PlatformAdmins
        description: Full access to all accounts

      - name: SecurityTeam
        description: Security tooling access

      - name: TeamAlpha
        description: Alpha team members

      - name: TeamBeta
        description: Beta team members

      - name: DataEngineers
        description: Data team members

    # Permission sets - team-specific access
    permissionSets:
      - name: AdministratorAccess
        description: Full administrator access
        sessionDuration: PT4H
        managedPolicies:
          - arn:aws:iam::aws:policy/AdministratorAccess
        assignToGroups:
          - PlatformAdmins
        assignToAccounts:
          - acme-platform
          - acme-security
          - acme-alpha
          - acme-beta
          - acme-data

      - name: SecurityAudit
        description: Security audit access
        sessionDuration: PT4H
        managedPolicies:
          - arn:aws:iam::aws:policy/SecurityAudit
        assignToGroups:
          - SecurityTeam
        assignToAccounts:
          - acme-security
          - acme-alpha
          - acme-beta
          - acme-data

      # Team-specific access - each team only gets access to their account
      - name: AlphaAccess
        description: Team Alpha access
        sessionDuration: PT8H
        managedPolicies:
          - arn:aws:iam::aws:policy/PowerUserAccess
        assignToGroups:
          - TeamAlpha
        assignToAccounts:
          - acme-alpha

      - name: BetaAccess
        description: Team Beta access
        sessionDuration: PT8H
        managedPolicies:
          - arn:aws:iam::aws:policy/PowerUserAccess
        assignToGroups:
          - TeamBeta
        assignToAccounts:
          - acme-beta

      - name: DataAccess
        description: Data team access
        sessionDuration: PT8H
        managedPolicies:
          - arn:aws:iam::aws:policy/PowerUserAccess
        assignToGroups:
          - DataEngineers
        assignToAccounts:
          - acme-data

  # ---------------------------------------------------------------------------
  # IPAM - Pools shared with Teams OU
  # ---------------------------------------------------------------------------
  ipam:
    delegatedAdminAccount: acme-platform
    region: us-east-1
    operatingRegions:
      - us-east-1

    pools:
      # ==========================================================================
      # IPv4 Pools - Global → Regional → shared with Teams OU
      # ==========================================================================
      ipv4:
        # Global pool - top of hierarchy
        - name: ipv4-global
          cidr: 10.0.0.0/8
          allocations:
            netmaskLength:
              default: 12
          description: Global IPv4 pool

        # Regional pool - shared with all teams
        - name: ipv4-us-east-1
          sourcePoolRef: ipv4-global
          locale: us-east-1
          cidr: 10.0.0.0/12
          allocations:
            netmaskLength:
              default: 16
          ramShareTargets:
            - ou: Teams
          description: Regional IPv4 pool shared with Teams OU

        # Platform pool
        - name: ipv4-us-east-1-platform
          sourcePoolRef: ipv4-global
          locale: us-east-1
          cidr: 10.16.0.0/16
          allocations:
            netmaskLength:
              default: 20
          ramShareTargets:
            - account: acme-platform
          description: Platform IPv4 pool

      # ==========================================================================
      # IPv6 Pools - shared with Teams OU
      # ==========================================================================
      ipv6:
        ula:
          - name: ipv6-ula-global
            netmaskLength: 40
            allocations:
              netmaskLength:
                default: 44
            description: Global ULA IPv6 pool

          - name: ipv6-ula-us-east-1
            sourcePoolRef: ipv6-ula-global
            locale: us-east-1
            netmaskLength: 44
            allocations:
              netmaskLength:
                default: 56
            ramShareTargets:
              - ou: Teams
            description: Regional ULA IPv6 shared with Teams OU

        gua:
          - name: ipv6-gua-us-east-1
            locale: us-east-1
            netmaskLength: 52
            publicIpSource: amazon
            awsService: ec2
            allocations:
              netmaskLength:
                default: 56
            ramShareTargets:
              - ou: Teams
            description: Public IPv6 pool shared with Teams OU

  # ---------------------------------------------------------------------------
  # Network Defaults
  # ---------------------------------------------------------------------------
  networkDefaults:
    subnetLayout:
      availabilityZones: [a, b, c]
      public:
        enabled: true
        netmaskLength: 24
      private:
        enabled: true
        netmaskLength: 20
    nat:
      enabled: true
      strategy: SingleAz

  # ---------------------------------------------------------------------------
  # Networks - each team gets their own VPC
  # ---------------------------------------------------------------------------
  networks:
    # Team Alpha VPC
    - name: alpha
      account: acme-alpha
      region: us-east-1
      ipam:
        ipv4:
          poolRef: ipv4-us-east-1
          netmaskLength: 16
        ipv6Ula:
          poolRef: ipv6-ula-us-east-1
          netmaskLength: 56
      tags:
        team: alpha

    # Team Beta VPC
    - name: beta
      account: acme-beta
      region: us-east-1
      ipam:
        ipv4:
          poolRef: ipv4-us-east-1
          netmaskLength: 16
        ipv6Ula:
          poolRef: ipv6-ula-us-east-1
          netmaskLength: 56
      tags:
        team: beta

    # Data team VPC
    - name: data
      account: acme-data
      region: us-east-1
      ipam:
        ipv4:
          poolRef: ipv4-us-east-1
          netmaskLength: 16
        ipv6Ula:
          poolRef: ipv6-ula-us-east-1
          netmaskLength: 56
      tags:
        team: data

    # Platform VPC - shared tooling, CI/CD
    - name: platform
      account: acme-platform
      region: us-east-1
      ipam:
        ipv4:
          poolRef: ipv4-us-east-1-platform
          netmaskLength: 16
        ipv6Ula:
          poolRef: ipv6-ula-us-east-1
          netmaskLength: 56
      tags:
        team: platform
