# Multiple Teams: Growing from one team to two
# =============================================
# First expansion from individual to multi-team architecture:
# - AWS Organization for account management
# - Teams OU with accounts per team
# - IPAM pools shared to Teams OU
# - Each team gets their own dual-stack VPC
#
# This is the minimal multi-team setup:
# - 1 AWS Organization
# - 3 Organizational Units (Teams, Teams/Alpha, Teams/Beta)
# - 2 Team Accounts
# - 2 Groups (Administrators, per-team)
# - IPAM with hierarchical pools
# - VPCs in each team account
#
# Why account-per-team?
# - Blast radius isolation between teams
# - Clear cost attribution
# - Teams own their infrastructure

apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: Foundation
metadata:
  name: acme
  namespace: acme
spec:
  managementPolicies: ["*"]

  providerConfigRef:
    name: aws-management-account
    kind: ProviderConfig

  region: us-east-1

  tags:
    organization: acme
    managed-by: crossplane

  # ---------------------------------------------------------------------------
  # Organization Settings
  # ---------------------------------------------------------------------------
  organization:
    awsServiceAccessPrincipals:
      - iam.amazonaws.com
      - sso.amazonaws.com
      - account.amazonaws.com
      - ipam.amazonaws.com
      - ram.amazonaws.com

  # ---------------------------------------------------------------------------
  # Organizational Unit Hierarchy
  # ---------------------------------------------------------------------------
  organizationalUnits:
    - path: Teams
    - path: Teams/Alpha
    - path: Teams/Beta

  # ---------------------------------------------------------------------------
  # Team Accounts
  # ---------------------------------------------------------------------------
  accounts:
    - name: acme-alpha
      email: aws-alpha@acme.example.com
      ou: Teams/Alpha
      tags:
        team: alpha

    - name: acme-beta
      email: aws-beta@acme.example.com
      ou: Teams/Beta
      tags:
        team: beta

  # ---------------------------------------------------------------------------
  # Identity Center
  # ---------------------------------------------------------------------------
  identityCenter:
    region: us-east-1
    identityStoreId: d-1234567890
    instanceArn: arn:aws:sso:::instance/ssoins-abcdef0123456789

    groups:
      - name: Administrators
        description: Full access to all accounts

      - name: TeamAlpha
        description: Alpha team members

      - name: TeamBeta
        description: Beta team members

    permissionSets:
      - name: AdministratorAccess
        managedPolicies:
          - arn:aws:iam::aws:policy/AdministratorAccess
        assignToGroups:
          - Administrators
        assignToAccounts:
          - acme-alpha
          - acme-beta

      # Each team gets access to their account only
      - name: AlphaAccess
        sessionDuration: PT8H
        managedPolicies:
          - arn:aws:iam::aws:policy/PowerUserAccess
        assignToGroups:
          - TeamAlpha
        assignToAccounts:
          - acme-alpha

      - name: BetaAccess
        sessionDuration: PT8H
        managedPolicies:
          - arn:aws:iam::aws:policy/PowerUserAccess
        assignToGroups:
          - TeamBeta
        assignToAccounts:
          - acme-beta

  # ---------------------------------------------------------------------------
  # IPAM - Pools shared with Teams OU
  # ---------------------------------------------------------------------------
  ipam:
    region: us-east-1
    operatingRegions:
      - us-east-1

    pools:
      ipv4:
        - name: ipv4-global
          cidr: 10.0.0.0/8
          allocations:
            netmaskLength:
              default: 12

        # Regional pool shared with all teams
        - name: ipv4-us-east-1
          sourcePoolRef: ipv4-global
          locale: us-east-1
          cidr: 10.0.0.0/12
          allocations:
            netmaskLength:
              default: 16
          ramShareTargets:
            - ou: Teams

      ipv6:
        ula:
          - name: ipv6-ula-global
            netmaskLength: 40
            allocations:
              netmaskLength:
                default: 44

          - name: ipv6-ula-us-east-1
            sourcePoolRef: ipv6-ula-global
            locale: us-east-1
            netmaskLength: 44
            allocations:
              netmaskLength:
                default: 56
            ramShareTargets:
              - ou: Teams

        gua:
          - name: ipv6-gua-us-east-1
            locale: us-east-1
            netmaskLength: 52
            publicIpSource: amazon
            awsService: ec2
            allocations:
              netmaskLength:
                default: 56
            ramShareTargets:
              - ou: Teams

  # ---------------------------------------------------------------------------
  # Networks - each team gets their own VPC
  # ---------------------------------------------------------------------------
  networks:
    # Team Alpha VPC
    - name: alpha
      account: acme-alpha
      region: us-east-1
      ipam:
        ipv4:
          poolRef: ipv4-us-east-1
          netmaskLength: 16
        ipv6Ula:
          poolRef: ipv6-ula-us-east-1
          netmaskLength: 56
      subnetLayout:
        availabilityZones: [a, b, c]
        public:
          enabled: true
          netmaskLength: 24
        private:
          enabled: true
          netmaskLength: 20
      nat:
        enabled: true
        strategy: SingleAz
      tags:
        team: alpha

    # Team Beta VPC
    - name: beta
      account: acme-beta
      region: us-east-1
      ipam:
        ipv4:
          poolRef: ipv4-us-east-1
          netmaskLength: 16
        ipv6Ula:
          poolRef: ipv6-ula-us-east-1
          netmaskLength: 56
      subnetLayout:
        availabilityZones: [a, b, c]
        public:
          enabled: true
          netmaskLength: 24
        private:
          enabled: true
          netmaskLength: 20
      nat:
        enabled: true
        strategy: SingleAz
      tags:
        team: beta
