name: on-pr

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - ".github/workflows/on-pr.yaml"
      - ".gitops/**"
      - "apis/**"
      - "examples/**"
      - "tests/**"
      - "functions/**"
      - "upbound.yaml"

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v2.19.1
    with:
      examples: |
        [
          { "example": "examples/foundations/minimal.yaml" },
          { "example": "examples/foundations/individual.yaml" },
          { "example": "examples/foundations/individual.yaml", "observed_resources": "examples/test/mocks/observed-resources/individual/steps/1" },
          { "example": "examples/foundations/enterprise.yaml" },
          { "example": "examples/foundations/enterprise.yaml", "observed_resources": "examples/test/mocks/observed-resources/enterprise/steps/1" },
          { "example": "examples/foundations/import-existing.yaml" },
          { "example": "examples/foundations/with-networks.yaml" },
          { "example": "examples/foundations/with-ram-shares.yaml" }
        ]
      api_path: apis/foundations
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v2.19.1

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v2.19.1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      aws: true
      aws-use-oidc: true
      aws-account-id: "034489662075"
      aws-region: us-east-2
      timeout-minutes: 33
      debug-resource-types: |
        [
          "organizations.aws.hops.ops.com.ai",
          "identitycenters.aws.hops.ops.com.ai",
          "ipams.aws.hops.ops.com.ai",
          "accounts.aws.hops.ops.com.ai"
        ]
      env-vars: |
        {
          "ORG_ID": "o-3lholziq1o",
          "TEST_OU_EXTERNAL_NAME": "ou-hdvp-fbcb7sbw",
          "TEST_ACCOUNT_EXTERNAL_NAME": "544051101726",
          "IDENTITY_STORE_ID": "d-9a675288a4",
          "SSO_INSTANCE_ARN": "arn:aws:sso:::instance/ssoins-668444b406cda8b2",
          "IC_GROUP_NAME": "Admins",
          "IC_GROUP_ID": "710b35f0-2061-7026-da5c-b5cd9f22002d",
          "IC_PERMISSION_SET_NAME": "AdminAccess",
          "IC_PERMISSION_SET_ARN": "arn:aws:sso:::permissionSet/ssoins-668444b406cda8b2/ps-4751b925ba450440",
          "IPAM_ID": "ipam-0573c7815d0a36e00",
          "IPAM_POOL_GLOBAL_IPV4": "ipam-pool-0a82c73b97dc0dabb",
          "IPAM_POOL_REGIONAL_IPV4": "ipam-pool-0607416fa3707147a",
          "IPAM_POOL_GLOBAL_IPV6": "ipam-pool-02261bfded584dbfb",
          "IPAM_POOL_REGIONAL_IPV6": "ipam-pool-0ca730678e463dbfc",
          "NETWORK_VPC": "vpc-0c20c458dcb738f21",
          "NETWORK_IGW": "igw-0a11d99e3cc584333",
          "NETWORK_EIGW": "eigw-02d33bcb5e87d8353",
          "NETWORK_SUBNET_PRIVATE_A": "subnet-0ba2f584c25e9435d",
          "NETWORK_SUBNET_PRIVATE_B": "subnet-02e4d512f8859e684",
          "NETWORK_SUBNET_PRIVATE_C": "subnet-0a46f41be19e3ef54",
          "NETWORK_SUBNET_PUBLIC_A": "subnet-0f17f94da9c13d3fe",
          "NETWORK_SUBNET_PUBLIC_B": "subnet-0f09414e8042cbee9",
          "NETWORK_SUBNET_PUBLIC_C": "subnet-0739c3679702306eb",
          "NETWORK_RT_PUBLIC": "rtb-0ec6e6b72b4069f6d",
          "NETWORK_RT_PRIVATE_A": "rtb-0123083a1a6980352",
          "NETWORK_RT_PRIVATE_B": "rtb-0f3651ed2fa86b78c",
          "NETWORK_RT_PRIVATE_C": "rtb-00bcd173ff8e26c91",
          "NETWORK_RTA_PUBLIC_A": "rtbassoc-0f55cb72f58eba3c6",
          "NETWORK_RTA_PUBLIC_B": "rtbassoc-0e260598fc03c1bda",
          "NETWORK_RTA_PUBLIC_C": "rtbassoc-0ed529b17080a7ff5",
          "NETWORK_RTA_PRIVATE_A": "rtbassoc-05a8500db23f7e5c4",
          "NETWORK_RTA_PRIVATE_B": "rtbassoc-04181252701b445f0",
          "NETWORK_RTA_PRIVATE_C": "rtbassoc-0f81cf5c3e798aa8c"
        }

  publish:
    needs:
      - validate
      - test
    uses: unbounded-tech/workflows-crossplane/.github/workflows/publish.yaml@v2.19.1
    secrets: inherit
    with:
      tag: pr-${{ github.event.pull_request.number }}-${{ github.sha }}
