name: on-pr

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - ".github/workflows/on-pr.yaml"
      - ".gitops/**"
      - "apis/**"
      - "examples/**"
      - "tests/**"
      - "functions/**"
      - "upbound.yaml"

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v2.20.0
    with:
      examples: |
        [
          { "example": "examples/foundations/minimal.yaml" },
          { "example": "examples/foundations/individual.yaml" },
          { "example": "examples/foundations/individual.yaml", "observed_resources": "examples/test/mocks/observed-resources/individual/steps/1" },
          { "example": "examples/foundations/enterprise.yaml" },
          { "example": "examples/foundations/enterprise.yaml", "observed_resources": "examples/test/mocks/observed-resources/enterprise/steps/1" },
          { "example": "examples/foundations/import-existing.yaml" },
          { "example": "examples/foundations/with-networks.yaml" },
          { "example": "examples/foundations/with-ram-shares.yaml" }
        ]
      api_path: apis/foundations
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v2.20.0

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v2.19.1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      aws: true
      aws-use-oidc: true
      aws-account-id: "034489662075"
      aws-region: us-east-2
      timeout-minutes: 33
      debug-resource-types: |
        [
          "organizations.aws.hops.ops.com.ai",
          "identitycenters.aws.hops.ops.com.ai",
          "ipams.aws.hops.ops.com.ai",
          "accounts.aws.hops.ops.com.ai"
        ]
      write-env-files: true
      env-vars: |
        {
          "ORG_ID": "${{ vars.ORG_ID }}",
          "TEST_OU_EXTERNAL_NAME": "${{ vars.TEST_OU_EXTERNAL_NAME }}",
          "TEST_ACCOUNT_EXTERNAL_NAME": "${{ vars.TEST_ACCOUNT_EXTERNAL_NAME }}",
          "IDENTITY_STORE_ID": "${{ vars.IDENTITY_STORE_ID }}",
          "SSO_INSTANCE_ARN": "${{ vars.SSO_INSTANCE_ARN }}",
          "IC_GROUP_NAME": "${{ vars.IC_GROUP_NAME }}",
          "IC_GROUP_ID": "${{ vars.IC_GROUP_ID }}",
          "IC_PERMISSION_SET_NAME": "${{ vars.IC_PERMISSION_SET_NAME }}",
          "IC_PERMISSION_SET_ARN": "${{ vars.IC_PERMISSION_SET_ARN }}",
          "IPAM_ID": "${{ vars.IPAM_ID }}",
          "IPAM_POOL_GLOBAL_IPV4": "${{ vars.IPAM_POOL_GLOBAL_IPV4 }}",
          "IPAM_POOL_REGIONAL_IPV4": "${{ vars.IPAM_POOL_REGIONAL_IPV4 }}",
          "IPAM_POOL_GLOBAL_IPV6": "${{ vars.IPAM_POOL_GLOBAL_IPV6 }}",
          "IPAM_POOL_REGIONAL_IPV6": "${{ vars.IPAM_POOL_REGIONAL_IPV6 }}",
          "NETWORK_VPC": "${{ vars.NETWORK_VPC }}",
          "NETWORK_IGW": "${{ vars.NETWORK_IGW }}",
          "NETWORK_EIGW": "${{ vars.NETWORK_EIGW }}",
          "NETWORK_SUBNET_PRIVATE_A": "${{ vars.NETWORK_SUBNET_PRIVATE_A }}",
          "NETWORK_SUBNET_PRIVATE_B": "${{ vars.NETWORK_SUBNET_PRIVATE_B }}",
          "NETWORK_SUBNET_PRIVATE_C": "${{ vars.NETWORK_SUBNET_PRIVATE_C }}",
          "NETWORK_SUBNET_PUBLIC_A": "${{ vars.NETWORK_SUBNET_PUBLIC_A }}",
          "NETWORK_SUBNET_PUBLIC_B": "${{ vars.NETWORK_SUBNET_PUBLIC_B }}",
          "NETWORK_SUBNET_PUBLIC_C": "${{ vars.NETWORK_SUBNET_PUBLIC_C }}",
          "NETWORK_RT_PUBLIC": "${{ vars.NETWORK_RT_PUBLIC }}",
          "NETWORK_RT_PRIVATE_A": "${{ vars.NETWORK_RT_PRIVATE_A }}",
          "NETWORK_RT_PRIVATE_B": "${{ vars.NETWORK_RT_PRIVATE_B }}",
          "NETWORK_RT_PRIVATE_C": "${{ vars.NETWORK_RT_PRIVATE_C }}",
          "NETWORK_RTA_PUBLIC_A": "${{ vars.NETWORK_RTA_PUBLIC_A }}",
          "NETWORK_RTA_PUBLIC_B": "${{ vars.NETWORK_RTA_PUBLIC_B }}",
          "NETWORK_RTA_PUBLIC_C": "${{ vars.NETWORK_RTA_PUBLIC_C }}",
          "NETWORK_RTA_PRIVATE_A": "${{ vars.NETWORK_RTA_PRIVATE_A }}",
          "NETWORK_RTA_PRIVATE_B": "${{ vars.NETWORK_RTA_PRIVATE_B }}",
          "NETWORK_RTA_PRIVATE_C": "${{ vars.NETWORK_RTA_PRIVATE_C }}"
        }

  publish:
    needs:
      - validate
      - test
    uses: unbounded-tech/workflows-crossplane/.github/workflows/publish.yaml@v2.20.0
    secrets: inherit
    with:
      tag: pr-${{ github.event.pull_request.number }}-${{ github.sha }}
